//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDirectiva.Presentacion.Resource.Mensaje {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajeResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDirectiva.Presentacion.Resource.Mensaje.MensajeResource", typeof(MensajeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario Válido.
        /// </summary>
        public static string ComentarioValido {
            get {
                return ResourceManager.GetString("ComentarioValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de activar el registro?.
        /// </summary>
        public static string ConfirmacionActivacion {
            get {
                return ResourceManager.GetString("ConfirmacionActivacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar el registro?.
        /// </summary>
        public static string ConfirmacionEliminacion {
            get {
                return ResourceManager.GetString("ConfirmacionEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de grabar los cambios solicitados?.
        /// </summary>
        public static string ConfirmacionGuardar {
            get {
                return ResourceManager.GetString("ConfirmacionGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una fecha..
        /// </summary>
        public static string DebeSeleccionarFecha {
            get {
                return ResourceManager.GetString("DebeSeleccionarFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos un registro..
        /// </summary>
        public static string DebeSeleccionarRegistro {
            get {
                return ResourceManager.GetString("DebeSeleccionarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar sólo un registro..
        /// </summary>
        public static string DebeSeleccionarUnRegistro {
            get {
                return ResourceManager.GetString("DebeSeleccionarUnRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al grabar el registro..
        /// </summary>
        public static string ErroralGrabar {
            get {
                return ResourceManager.GetString("ErroralGrabar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View model no definido..
        /// </summary>
        public static string ErrorCargarViewModel {
            get {
                return ResourceManager.GetString("ErrorCargarViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error inesperado. Inténtelo nuevamente.
        /// </summary>
        public static string EtiquetaErrorRegistro {
            get {
                return ResourceManager.GetString("EtiquetaErrorRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario estará activo hasta.
        /// </summary>
        public static string EtiquetaMensajeDesactivar {
            get {
                return ResourceManager.GetString("EtiquetaMensajeDesactivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ejecuto ningun proceso..
        /// </summary>
        public static string EtiquetaNoEjecutoNingunProceso {
            get {
                return ResourceManager.GetString("EtiquetaNoEjecutoNingunProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Demanda ya existe.
        /// </summary>
        public static string ExistenciaCodigoDemanda {
            get {
                return ResourceManager.GetString("ExistenciaCodigoDemanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de depósito distinto..
        /// </summary>
        public static string FechaRegistroDistinta {
            get {
                return ResourceManager.GetString("FechaRegistroDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe de pago distinto..
        /// </summary>
        public static string ImportePagoDistinta {
            get {
                return ResourceManager.GetString("ImportePagoDistinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar al menos un filtro de búsqueda..
        /// </summary>
        public static string InformacionIngresarFiltro {
            get {
                return ResourceManager.GetString("InformacionIngresarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información mostrada corresponde a la.
        /// </summary>
        public static string InformacionPreFiltro {
            get {
                return ResourceManager.GetString("InformacionPreFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud no ha podido ser procesada. Comuníquese con el Administrador del Sistema..
        /// </summary>
        public static string MensajeException {
            get {
                return ResourceManager.GetString("MensajeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña autogenerada es:.
        /// </summary>
        public static string MensajeLaContraseniaAutogeneradaEs {
            get {
                return ResourceManager.GetString("MensajeLaContraseniaAutogeneradaEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un archivo, verifique..
        /// </summary>
        public static string MensajeValidarElegirArchivo {
            get {
                return ResourceManager.GetString("MensajeValidarElegirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo elegido no tiene la extensión permitida, verifique..
        /// </summary>
        public static string MensajeValidarExtensionArchivo {
            get {
                return ResourceManager.GetString("MensajeValidarExtensionArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los registros seleccionados no coinciden:.
        /// </summary>
        public static string RegistrosNoCoinciden {
            get {
                return ResourceManager.GetString("RegistrosNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se activó el registro con éxito..
        /// </summary>
        public static string SeActivoRegistro {
            get {
                return ResourceManager.GetString("SeActivoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se anuló registro con éxito..
        /// </summary>
        public static string SeAnuloRegistro {
            get {
                return ResourceManager.GetString("SeAnuloRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminó el registro con éxito..
        /// </summary>
        public static string SeEliminoRegistro {
            get {
                return ResourceManager.GetString("SeEliminoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se guardó la información con éxito..
        /// </summary>
        public static string SeGuardoInformacionExito {
            get {
                return ResourceManager.GetString("SeGuardoInformacionExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al menos un parámetro de filtro correcto.
        /// </summary>
        public static string SeleccioneFiltro {
            get {
                return ResourceManager.GetString("SeleccioneFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se cargaron.
        /// </summary>
        public static string Texto1 {
            get {
                return ResourceManager.GetString("Texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a registros con éxito y.
        /// </summary>
        public static string Texto2 {
            get {
                return ResourceManager.GetString("Texto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sin éxito..
        /// </summary>
        public static string Texto3 {
            get {
                return ResourceManager.GetString("Texto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor confirme la eliminación de los registros seleccionados..
        /// </summary>
        public static string TextoEliminacion {
            get {
                return ResourceManager.GetString("TextoEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor confirme la activación del registro..
        /// </summary>
        public static string TextoReactivacion {
            get {
                return ResourceManager.GetString("TextoReactivacion", resourceCulture);
            }
        }
    }
}
